---
title: "EDA and some fittings"
author: "Entong Li"
date: "4/2/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F, warning = F)
library(rpart)
library(rpart.plot)
library(ggplot2)
library(randomForest)
library(gbm)
library(GGally)
library(knitr)
library(dplyr)
library(gridExtra)
```

# EDA:

```{r}
data <- read.csv("trainData.csv", header = T)
data <- data[,-233]
response <- read.csv("train_outcome.csv",header = T)
data <- merge(data, response, by.x = "RecordID", by.y = "id")
train.id <- sample(data$RecordID, 0.7*dim(data)[1], replace = F)
train <- data[train.id,]
test <- data[-train.id,]
testNames = c("ALP", "ALT", "AST","Albumin","BUN","Bilirubin",
             "Cholesterol","Creatinine","DiasABP","FiO2","GCS",
             "Glucose","HCO3","HCT","HR","K","Lactate","MAP",
             "MechVent","Mg","NIDiasABP","NIMAP","NISysABP","Na",
             "PaCO2","PaO2","Platelets","RespRate","SAPS","SaO2",
             "SysABP","Temp","TroponinI","TroponinT","Urine","WBC",
             "noLabel","pH")
```

## Summary of Mean:

```{r}
summary(data[,seq(5,227,by=6)])
```


## Summary of Max:

```{r}
summary(data[,seq(6,228,by=6)])
```



## Summary of Min:

```{r}
summary(data[,seq(7,229,by=6)])
```


## Summary of Range:

```{r}
summary(data[,seq(8,230,by=6)])
```


## Summary of changeStoF:

```{r}
summary(data[,seq(9,231,by=6)])
```



## Summary of numTest:

```{r}
summary(data[,seq(10,232,by=6)])
```


```{r}
naM <- matrix(rep(NA, 38*2), nrow = 38, ncol = 2, dimnames = list(c(testNames), c("NA","Percentage of NA")))
n <- dim(data)[1]
for (i in 1:38) {
  na <- sum(is.na(data[,4+i*6]))
  naM[i,1] <- na
  naM[i,2] <- na/n
}
naM
```


# Explore whether the high percentage of NA will affect the outcome.

```{r}
train.n <- dim(train)[1]
newdat <- train$RecordID
for (i in 1:38) {
  newcol <- ifelse(is.na(train[,4+i*6]),0, 1)
  newdat <- cbind(newdat, newcol)
}
newdat <- as.data.frame(newdat)
names(newdat)[2:39] <- testNames
names(newdat)[1] <- "id"
newdat <- merge(newdat, response, by="id")
testnewdat <- test$RecordID
for (i in 1:38) {
  newcol <- ifelse(is.na(test[,4+i*6]),0, 1)
  testnewdat <- cbind(testnewdat, newcol)
}
testnewdat <- as.data.frame(testnewdat)
names(testnewdat)[2:39] <- testNames
names(testnewdat)[1] <- "id"
testnewdat <- merge(testnewdat, response, by="id")
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = ALP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = ALT, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = AST, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Albumin, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = BUN, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Bilirubin, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Cholesterol, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Creatinine, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```



```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = DiasABP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = FiO2, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = GCS, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Glucose, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = HCO3, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = HCT, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = HR, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = K, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```



```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Lactate, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = MAP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = MechVent, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Mg, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = NIDiasABP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = NIMAP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = NISysABP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Na, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = PaCO2, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = PaO2, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Platelets, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = RespRate, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = SAPS, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = SaO2, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = SysABP, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Temp, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = TroponinI, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = TroponinT, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = Urine, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p4 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = WBC, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3,p4, nrow = 2)
```


```{r}
p1 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = noLabel, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p2 <- ggplot(data = newdat) + 
  geom_bar(mapping = aes(x = pH, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
p3 <- ggplot(data = data) + 
  geom_bar(mapping = aes(x = AdmissionType, y = ..prop.., group = outcome, fill = outcome), stat = "count") + 
  scale_y_continuous(labels = scales::percent_format()) + facet_wrap(~outcome)
grid.arrange(p1,p2,p3, nrow = 2)
```


```{r}
newdat$outcome <- factor(newdat$outcome)
levels(newdat$outcome) = c("Negative","Positive")
rf1 <- randomForest(outcome~., data = newdat[,-1], mtry = floor(sqrt(38)),
                       importance = TRUE)
importance(rf1)
```

```{r}
testnewdat$outcome <- factor(testnewdat$outcome)
levels(testnewdat$outcome) = c("Negative","Positive")
rf_test_pred = predict(rf1, newdata = testnewdat)
rf_test_err = mean(rf_test_pred!=testnewdat$outcome)
rf_test_err
```

```{r, fig.height=7}
varImpPlot(rf1,n.var=38)
```


