---
output: pdf_document
---
# Data challenge
Group members. Brody Erlandson, Entong Li, Jiwoong Kang

### load package & response
```{r results = FALSE, message = FALSE, echo = FALSE, warning = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(GGally)
library(class)

response <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\train_outcome.csv")
# head(response)

response$outcome <- factor(response$outcome)
levels(response$outcome) <- c("recovered", "notRecovered")
names(response)[names(response) == "id"] <- "RecordID"
```

### merging variables & response
```{r message = FALSE, echo = FALSE, warning = FALSE}
overallData <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\trainData.csv")
overallData <- merge(response, overallData, by.x = "RecordID")

# ggpairs(overallData[,c("outcome","Age")], mapping = ggplot2::aes(colour=outcome))
# ggpairs(overallData[,c("outcome","Gender")], mapping = ggplot2::aes(colour=outcome))
# ggpairs(overallData[,c("outcome","AdmissionType")], mapping = ggplot2::aes(colour=outcome))
```

### split train & test data
```{r message = FALSE, echo = FALSE, warning = FALSE}
trainId <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\trainInd.txt")
trainId = trainId$X4102
  # set.seed(1)
  # num = dim(overallData)[1]
  # id.train = sample(seq(1, num), size = num * 0.7)
trainData = overallData[trainId, ]
testData = overallData[-trainId, ]
```

### filling missing values for train set
```{r message = FALSE, echo = FALSE, warning = FALSE}
trainData_recover = subset(trainData, outcome == "recovered")
trainData_notRecover = subset(trainData, outcome == "notRecovered")

# filling_median <- c("mean")
# filling_zero <- c("range","numTest","changeStoF")
for (i in 6:dim(trainData)[2]){
  
  if (grepl("mean", colnames(trainData)[i])){
      trainData_recover[is.na(trainData_recover[,i]),c(i,i+1,i+2)] = median(trainData_recover[!is.na(trainData_recover[,i]),i])
      trainData_notRecover[is.na(trainData_notRecover[,i]),c(i,i+1,i+2)] = median(trainData_recover[!is.na(trainData_recover[,i]),i])

  } else if (grepl("range", colnames(trainData)[i])| grepl("numTest", colnames(trainData)[i]) | grepl("changeStoF", colnames(trainData)[i])) {
      trainData_recover[is.na(trainData_recover[,i]),i] =0
      trainData_notRecover[is.na(trainData_notRecover[,i]),i] =0
  }

}

trainData <- full_join(trainData_recover, trainData_notRecover)
```


### filling missing values for test set
```{r message = FALSE, echo = FALSE, warning = FALSE}
trainData_recover = subset(testData, outcome == "recovered")
trainData_notRecover = subset(testData, outcome == "notRecovered")

# filling_median <- c("mean")
# filling_zero <- c("range","numTest","changeStoF")
for (i in 6:dim(testData)[2]){
  
  if (grepl("mean", colnames(testData)[i])){
      trainData_recover[is.na(trainData_recover[,i]),c(i,i+1,i+2)] = median(trainData_recover[!is.na(trainData_recover[,i]),i])
      trainData_notRecover[is.na(trainData_notRecover[,i]),c(i,i+1,i+2)] = median(trainData_recover[!is.na(trainData_recover[,i]),i])

  } else if (grepl("range", colnames(trainData)[i])| grepl("numTest", colnames(trainData)[i]) | grepl("changeStoF", colnames(trainData)[i])) {
      trainData_recover[is.na(trainData_recover[,i]),i] =0
      trainData_notRecover[is.na(trainData_notRecover[,i]),i] =0
  }

}

testData <- full_join(trainData_recover, trainData_notRecover)
```

```{r}
write.csv(trainData, "C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\trainData_imputed_outcome.csv", row.names = F)
write.csv(testData, "C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\testData_imputed_outcome.csv", row.names = F)
```