---
output: pdf_document
---
# Data challenge
Group members. Brody Erlandson, Entong Li, Jiwoong Kang

### load package & response
```{r results = FALSE, message = FALSE, echo = FALSE, warning = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(GGally)
library(class)

response <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\train_outcome.csv")
# head(response)

response$outcome <- factor(response$outcome)
levels(response$outcome) <- c("recovered", "notRecovered")
names(response)[names(response) == "id"] <- "RecordID"
```

### merging variables & response
```{r message = FALSE, echo = FALSE, warning = FALSE}
trainData <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\trainData.csv")
trainData <- merge(response, trainData, by.x = "RecordID")

# ggpairs(trainData[,c("outcome","Age")], mapping = ggplot2::aes(colour=outcome))
# ggpairs(trainData[,c("outcome","Gender")], mapping = ggplot2::aes(colour=outcome))
# ggpairs(trainData[,c("outcome","AdmissionType")], mapping = ggplot2::aes(colour=outcome))
```
### filling missing values
```{r message = FALSE, echo = FALSE, warning = FALSE}
trainData_admission_1_0 = subset(trainData, AdmissionType == 1 & outcome == "recovered")
trainData_admission_1_1 = subset(trainData, AdmissionType == 1 & outcome == "notRecovered")
trainData_admission_2_0 = subset(trainData, AdmissionType == 2 & outcome == "recovered")
trainData_admission_2_1 = subset(trainData, AdmissionType == 2 & outcome == "notRecovered")
trainData_admission_3_0 = subset(trainData, AdmissionType == 3 & outcome == "recovered")
trainData_admission_3_1 = subset(trainData, AdmissionType == 3 & outcome == "notRecovered")
trainData_admission_4_0 = subset(trainData, AdmissionType == 4 & outcome == "recovered")
trainData_admission_4_1 = subset(trainData, AdmissionType == 4 & outcome == "notRecovered")

# filling_median <- c("mean")
# filling_zero <- c("range","numTest","changeStoF")
for (i in 6:dim(trainData)[2]){
  
  if (grepl("mean", colnames(trainData)[i])){
      trainData_admission_1_0[is.na(trainData_admission_1_0[,i]),c(i,i+1,i+2)] = median(trainData_admission_1_0[!is.na(trainData_admission_1_0[,i]),i])
      trainData_admission_1_1[is.na(trainData_admission_1_1[,i]),c(i,i+1,i+2)] = median(trainData_admission_1_1[!is.na(trainData_admission_1_1[,i]),i])
      trainData_admission_2_0[is.na(trainData_admission_2_0[,i]),c(i,i+1,i+2)] = median(trainData_admission_2_0[!is.na(trainData_admission_2_0[,i]),i])
      trainData_admission_2_1[is.na(trainData_admission_2_1[,i]),c(i,i+1,i+2)] = median(trainData_admission_2_1[!is.na(trainData_admission_2_1[,i]),i])
      trainData_admission_3_0[is.na(trainData_admission_3_0[,i]),c(i,i+1,i+2)] = median(trainData_admission_3_0[!is.na(trainData_admission_3_0[,i]),i])
      trainData_admission_3_1[is.na(trainData_admission_3_1[,i]),c(i,i+1,i+2)] = median(trainData_admission_3_1[!is.na(trainData_admission_3_1[,i]),i])
      trainData_admission_4_0[is.na(trainData_admission_4_0[,i]),c(i,i+1,i+2)] = median(trainData_admission_4_0[!is.na(trainData_admission_4_0[,i]),i])
      trainData_admission_4_1[is.na(trainData_admission_4_1[,i]),c(i,i+1,i+2)] = median(trainData_admission_4_1[!is.na(trainData_admission_4_1[,i]),i])
  } else if (grepl("range", colnames(trainData)[i])| grepl("numTest", colnames(trainData)[i]) | grepl("changeStoF", colnames(trainData)[i])) {
      trainData_admission_1_0[is.na(trainData_admission_1_0[,i]),i] =0
      trainData_admission_1_1[is.na(trainData_admission_1_1[,i]),i] =0
      trainData_admission_2_0[is.na(trainData_admission_2_0[,i]),i] =0
      trainData_admission_2_1[is.na(trainData_admission_2_1[,i]),i] =0
      trainData_admission_3_0[is.na(trainData_admission_3_0[,i]),i] =0
      trainData_admission_3_1[is.na(trainData_admission_3_1[,i]),i] =0
      trainData_admission_4_0[is.na(trainData_admission_4_0[,i]),i] =0
      trainData_admission_4_1[is.na(trainData_admission_4_1[,i]),i] =0
  }

}

trainData <- full_join(trainData_admission_1_0, trainData_admission_1_1)
trainData <- full_join(trainData, trainData_admission_2_0, by.x = "RecordID")
trainData <- full_join(trainData, trainData_admission_2_1, by.x = "RecordID")
trainData <- full_join(trainData, trainData_admission_3_0, by.x = "RecordID")
trainData <- full_join(trainData, trainData_admission_3_1, by.x = "RecordID")
trainData <- full_join(trainData, trainData_admission_4_0, by.x = "RecordID")
trainData <- full_join(trainData, trainData_admission_4_1, by.x = "RecordID")
```

