---
output: pdf_document
---
# Data challenge
Group members. Brody Erlandson, Entong Li, Jiwoong Kang

### load package & imputed data
```{r results = FALSE, message = FALSE, echo = FALSE, warning = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(GGally)
library(class)
library(e1071)
library(ROCR)

trainData <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\BrodysImpute_Age_Outcome_Gender-trainSet.csv")
testData <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\BrodysImpute_Age_Outcome_Gender-testSet.csv")
response <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\train_outcome.csv", header = T)

trainData = merge(trainData, response, by.x = "RecordID",by.y = "id")
testData = merge(testData, response,by.x = "RecordID", by.y = "id")
testData$outcome <- factor(testData$outcome)
levels(testData$outcome) = c("Recover","No-recover")
trainData$outcome <- factor(trainData$outcome)
levels(trainData$outcome) = c("Recover","No-recover")
trainData = trainData[,-1]
testData = testData[,-1]

trainData[2] = scale(trainData[2])
trainData[4:(dim(trainData)[2]-1)] = scale(trainData[4:(dim(trainData)[2]-1)])

testData[2] = scale(testData[2])
testData[4:(dim(testData)[2]-1)] = scale(testData[4:(dim(testData)[2]-1)])

trainData[is.na(trainData)] = 0
testData[is.na(testData)] = 0
```

## SVM fitting

### kernal simple SVM - radial
```{r message = FALSE, echo = FALSE, warning = FALSE}
train.t1 = trainData%>%filter(AdmissionType == 1)
train.t2 = trainData%>%filter(AdmissionType == 2)
train.t3 = trainData%>%filter(AdmissionType == 3)
train.t4 = trainData%>%filter(AdmissionType == 4)
test.t1 = testData%>%filter(AdmissionType == 1)
test.t2 = testData%>%filter(AdmissionType == 2)
test.t3 = testData%>%filter(AdmissionType == 3)
test.t4 = testData%>%filter(AdmissionType == 4)


svmfit1 = svm(outcome ~ ., data=train.t1, kernel="radial", gamma=0.01, cost=1, scale=FALSE)
test_pred = predict(svmfit1, newdata = test.t1[-dim(trainData)[2]])
test_accuracy1 = sum(test_pred == test.t1$outcome)/length(test_pred)
test_accuracy1
pr1 <- prediction(as.numeric(test_pred), as.numeric(test.t1$outcome))
auc1 = performance(pr1, "auc")
auc1@y.name
auc1@y.values
cm1 = table(test.t1$outcome,test_pred)
cm1


svmfit2 = svm(outcome ~ ., data=train.t2, kernel="radial", gamma=0.01, cost=1, scale=FALSE)
test_pred = predict(svmfit2, newdata = test.t2[-dim(trainData)[2]])
test_accuracy2 = sum(test_pred == test.t2$outcome)/length(test_pred)
test_accuracy2
pr2 <- prediction(as.numeric(test_pred), as.numeric(test.t2$outcome))
auc2 = performance(pr2, "auc")
auc2@y.name
auc2@y.values
cm2 = table(test.t2$outcome,test_pred)
cm2


svmfit3 = svm(outcome ~ ., data=train.t3, kernel="radial", gamma=0.01, cost=1, scale=FALSE)
test_pred = predict(svmfit3, newdata = test.t3[-dim(trainData)[2]])
test_accuracy3 = sum(test_pred == test.t3$outcome)/length(test_pred)
test_accuracy3
pr3 <- prediction(as.numeric(test_pred), as.numeric(test.t3$outcome))
auc3 = performance(pr3, "auc")
auc3@y.name
auc3@y.values
cm3 = table(test.t3$outcome,test_pred)
cm3


svmfit4 = svm(outcome ~ ., data=train.t4, kernel="radial", gamma=0.01, cost=1, scale=FALSE)
test_pred = predict(svmfit4, newdata = test.t4[-dim(trainData)[2]])
test_accuracy4 = sum(test_pred == test.t4$outcome)/length(test_pred)
test_accuracy4
pr4 <- prediction(as.numeric(test_pred), as.numeric(test.t4$outcome))
auc4 = performance(pr4, "auc")
auc4@y.name
auc4@y.values
cm4 = table(test.t4$outcome,test_pred)
cm4


svmfit = svm(outcome ~ ., data=trainData, kernel="radial", gamma=0.01, cost=1, scale=FALSE)
test_pred = predict(svmfit, newdata = testData[-dim(trainData)[2]])
test_accuracy = sum(test_pred == testData$outcome)/length(test_pred)
test_accuracy
pr <- prediction(as.numeric(test_pred), as.numeric(testData$outcome))
auc = performance(pr, "auc")
auc@y.name
auc@y.values
cm = table(testData$outcome,test_pred)
cm

```

### BER
```{r message = FALSE, echo = FALSE, warning = FALSE}
Recover =  (22 + 98 + 77 + 94) / (320+397)
Norecover = (469+358+285+136) / (175+1235)

BER_svm = 1 - ((Recover+Norecover)/2)
BER_svm
```

## tuning process performed beforehand

### kernal SVM - radial
```{r message = FALSE, echo = FALSE, warning = FALSE}
tune.out =tune(svm,outcome ~ .,data=trainData,tunecontrol=tune.control(cross=5),ranges=list(cost=c(1,10,100,1000), gamma=c(0.0001,0.001,0.01,0.1), kernel=c("radial")))

df_results = tune.out$performances
df_results[order(df_results$error),][1:3,]

test_pred = predict(tune.out$best.model, newdata = testData)
test_accuracy = sum(test_pred == testData$outcome)/length(test_pred)
test_accuracy
```

### kernal SVM - poly
```{r message = FALSE, echo = FALSE, warning = FALSE}
tune.out =tune(svm,outcome ~ .,data=trainData,tunecontrol=tune.control(cross=5),ranges=list(cost=c(1,10,100,1000), gamma=c(0.0001,0.001,0.01,0.1), degree=c(1,2,3), kernel=c("polynomial")))

df_results = tune.out$performances
df_results[order(df_results$error),][1:3,]

test_pred = predict(tune.out$best.model, newdata = testData)
test_accuracy = sum(test_pred == testData$outcome)/length(test_pred)
test_accuracy
```






