---
output: pdf_document
---
# Data challenge
Group members. Brody Erlandson, Entong Li, Jiwoong Kang

## EDA Jiwoong Kang (noLabel ~ WBC)

### load package & response
```{r results = FALSE, message = FALSE, echo = FALSE, warning = FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(GGally)
library(class)

response <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\final_data\\train_outcome.csv")
# head(response)

response$outcome <- factor(response$outcome)
levels(response$outcome) <- c("recovered", "notRecovered")
```

### make function
```{r message = FALSE, echo = FALSE, warning = FALSE}
variFunc <- function(variName){
  fn = paste("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\EDA_Ji\\", variName, ".csv", sep="")
  variData <- read.csv(fn, header = FALSE)
  names(variData)[1:4] <- c("id", "age", "gender", "admission type")
  
  variData_final <- merge(variData[,1:4], response, by.x = "id")
  variData_data <- variData[,5:dim(variData)[2]]
  variData_final$mean = rowMeans(variData_data, na.rm = T)
  variData_final$max = apply(variData_data, 1, function(x) max(x, na.rm = T))
  variData_final$min = apply(variData_data, 1, function(x) min(x, na.rm = T))
  variData_final$numTest <- apply(variData_data, 1, function(x) length(which(!is.na(x))))
  
  ggpairs(variData_final[,c("outcome","gender","admission type", "mean","min","max",'numTest')], mapping = ggplot2::aes(colour=outcome)) + theme_bw()
}
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
variFunc("noLabel")
variFunc('PaCO2')
variFunc('PaO2')
variFunc('pH')
variFunc('Platelets')
variFunc('RespRate')
variFunc('SaO2')
# variFunc('SAPS')
variFunc('SysABP')
variFunc('Temp')
variFunc('TroponinI')
variFunc('TroponinT')
variFunc('Urine')
variFunc('WBC')
```

### SAPS
```{r message = FALSE, echo = FALSE, warning = FALSE}
SAPS <- read.csv("C:\\Users\\Jiwoong Kang\\Desktop\\Stats 503\\data challenge\\EDA_Ji\\noLabel.csv", header = FALSE)
# head(noLabel)
names(SAPS)[1:4] <- c("id", "age", "gender", "admission type")

SAPS_final <- merge(SAPS[,1:4], response, by.x = "id")
SAPS_data <- SAPS[,5:dim(SAPS)[2]]
SAPS_final$mean = rowMeans(SAPS_data, na.rm = T)
SAPS_final$max = apply(SAPS_data, 1, function(x) max(x, na.rm = T))
SAPS_final$min = apply(SAPS_data, 1, function(x) min(x, na.rm = T))
SAPS_final$numTest <- apply(SAPS_data, 1, function(x) length(which(!is.na(x))))

ggpairs(SAPS_final[,c("outcome","gender","admission type", "mean",'min','max','numTest')], mapping = ggplot2::aes(colour=outcome)) + theme_bw()
```
